The `micronaut-gcp-common` module includes basic setup for running applications on Google Cloud.

dependency:io.micronaut.gcp:micronaut-gcp-common[]

Prerequisites:

. You should have a http://console.cloud.google.com[Google Cloud Platform] project created
. https://cloud.google.com/sdk/install[Install gcloud CLI]
. Configure default project `gcloud config set project YOUR_PROJECT_ID`
. Authenticate with `gcloud auth login`
. Authenticate application default credential with `gcloud auth application-default login`

It's strongly recommended that you use a https://cloud.google.com/iam/docs/understanding-service-accounts[Service Account] for your application.

=== Google Project ID

The module features a base api:gcp.GoogleCloudConfiguration[] which you can use to configure or retrieve the GCP Project ID:

include::{includedir}configurationProperties/io.micronaut.gcp.GoogleCloudConfiguration.adoc[]

You can inject this bean and use the `getProjectId()` method to retrieve the configured or detected project ID.

=== Google Credentials

The module will setup a bean of exposing the `com.google.auth.oauth2.GoogleCredentials` instance that are either detected from the local environment or configured by api:gcp.credentials.GoogleCredentialsConfiguration[]:

include::{includedir}configurationProperties/io.micronaut.gcp.credentials.GoogleCredentialsConfiguration.adoc[]
