plugins {
    id "io.micronaut.build.internal.gcp-base"
    id("java-library")
    id "io.micronaut.build.internal.java-base"
}

dependencies {
    testAnnotationProcessor(platform(mn.micronaut.core.bom))
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(platform(mn.micronaut.core.bom))

    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.http.server.tck)
    testImplementation(mn.micronaut.jackson.databind)
    testImplementation(libs.junit.platform.engine)
    testImplementation(mnTest.junit.jupiter.engine)
    testImplementation(mnValidation.micronaut.validation)
    testRuntimeOnly(mnLogging.logback.classic)
}

tasks.named("test") {
    useJUnitPlatform()
}

