plugins {
    id("io.micronaut.build.internal.gcp-base")
    id("io.micronaut.test-resources")
}

dependencies {
    annotationProcessor(mn.micronaut.inject.java)
    compileOnly(libs.managed.functions.framework.api)
    compileOnly(projects.micronautGcpFunctionHttp)
    implementation(mn.reactor)
    implementation(mnJacksonXml.micronaut.jackson.xml)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(projects.micronautGcpPubsub)
    implementation(projects.micronautGcpSecretManager)
    testRuntimeOnly(mn.snakeyaml)
    testRuntimeOnly(mnLogging.logback.classic)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testRuntimeOnly(mnTest.junit.platform.launcher)
}

micronaut {
    importMicronautPlatform.set(false)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
