To add support for Google Cloud Pub/Sub to an existing project, add the following dependencies to your build.

dependency:micronaut-gcp-pubsub[groupId="io.micronaut.gcp"]

== Creating a Pub/Sub Publisher with @PubSubClient

To publish messages to Google Cloud Pub/Sub, just define an interface that is annotated with ann:gcp.pubsub.annotation.PubSubClient[].

snippet::io.micronaut.gcp.pubsub.quickstart.AnimalClient[tags="imports, clazz", source="main", project-base="doc-examples/example"]

<1> The ann:gcp.pubsub.annotation.PubSubClient[] annotation is used to designate this interface as a client
<2> The topic `animals` will be used to publish messages
<3> The method accepts one argument that will be used as message body

NOTE: Make sure your current GCP project has a topic named `animals` before starting the application.

At compile time Micronaut will create an implementation of the above interface. You can then inject that interface on your business methods via `@Inject` and use it.

snippet::io.micronaut.gcp.pubsub.quickstart.AnimalService[tags="imports, clazz", source="main", project-base="doc-examples/example"]

<1> Constructor based injection
<2> Your custom serialization logic


== Creating a Pub/Sub Subscriber with @PubSubListener

To listen to Pub/Sub messages you can use ann:gcp.pubsub.annotation.PubSubListener[] annotation on a class to mark it as a message listener.

The following example would listen on a subscription named `animals` that is configured to be attached to the topic of the previous example.

snippet::io.micronaut.gcp.pubsub.quickstart.AnimalListener[tags="imports, clazz", source="main", project-base="doc-examples/example"]

<1> Designates this class to be a message listener for Pub/Sub messages
<2> Messages routed to the `animals` subscription will be delivered to this method
<3> The method has a single argument that contains the serialized body of the Pub/Sub message
