It is common to want to take just a slice of a regular Micronaut HTTP server application and deploy it as a function.

=== Configuration

To facilitate this model, Micronaut GCP includes an additional module that allows you to use regular Micronaut annotations like `@Controller` and `@Get` to define your functions that can be deployed to cloud function.

With this model you need to add the `micronaut-gcp-function-http` dependency to your application:

dependency:io.micronaut.gcp:micronaut-gcp-function-http[version="{version}"]

And define the Google Function API as a development only dependency:

dependency:com.google.cloud.functions:functions-framework-api[version="1.0.1", scope="developmentOnly"]

=== Running Functions Locally

First to run the function locally you should then make the regular Micronaut server a `developmentOnly` dependency since it is not necessary to include it in the JAR file that will be deployed to Cloud Function:

dependency:io.micronaut:micronaut-http-server-netty[scope="developmentOnly"]

You can then use `./gradlew run` or `./mvnw compile exec:exec` to run the function locally using Micronaut's Netty-based server.

Alternatively, you could configure the https://github.com/GoogleCloudPlatform/functions-framework-java[Google Function Framework for Java] which includes a Maven plugin, or for Gradle include the following:

.Configuring the Function framework in Gradle
[source,groovy]
----

configurations {
    invoker
}

dependencies {
    invoker 'com.google.cloud.functions.invoker:java-function-invoker:1.0.0-beta1'
}


task('runFunction', type: JavaExec, dependsOn: classes) {
    main = 'com.google.cloud.functions.invoker.runner.Invoker'
    classpath(configurations.invoker)
    args(
            '--target', 'io.micronaut.gcp.function.http.HttpFunction',
            '--classpath', (configurations.runtimeClasspath + sourceSets.main.output).asPath,
            '--port', 8081

    )
}
----

With this in place you can run `./gradlew runFunction` to run the function locally.

=== Deployment

When deploying the function to Cloud Function you should use the api:gcp.function.http.HttpFunction[] class as the handler reference.

First build the function with:

```bash
$ ./gradlew clean shadowJar
```

Then `cd` into the `build/libs` directory (deployment has to be done from the location where the JAR file resides):

```bash
$ cd build/libs
```

To deploy the function make sure you have `gcloud` CLI then run:

```bash
$ gcloud beta functions deploy myfunction --entry-point io.micronaut.gcp.function.http.HttpFunction --runtime java11 --trigger-http
```

In the example above `myfunction` refers to the name of your function and can be changed to whatever name you prefer to name your function.

To obtain the trigger URL you can use the following command:

```bash
$ YOUR_HTTP_TRIGGER_URL=$(gcloud beta functions describe myfunction --format='value(httpsTrigger.url)')
```

You can then use this variable to test the function invocation:

```bash
$ curl -i $YOUR_HTTP_TRIGGER_URL/hello/John
```


