Micronaut GCP offers two ways to write cloud functions with Micronaut. The first way is more low level and involves using Micronaut's built in support for functions. Simply add the following dependency to your classpath:

dependency:io.micronaut.gcp:micronaut-gcp-function[]

Then add the Cloud Function API as a `compileOnly` dependency (`provided` with Maven):

dependency:com.google.cloud.functions:functions-framework-api[version="1.0.1", scope="compileOnly"]

Now define a class that implements one of Google Cloud Found's interfaces, for example `com.google.cloud.functions.BackgroundFunction`, and extends from `io.micronaut.function.executor.FunctionInitializer`.

The following is an example of a `BackgroundFunction` that uses Micronaut and Google Cloud Function:

snippet::example.background.Example[project-base="doc-examples/example", source="main"]

<1> The function extends from `io.micronaut.function.executor.FunctionInitializer`
<2> The function implements `com.google.cloud.functions.BackgroundFunction`
<3> Dependency injection can be used on the fields

When you extend from `FunctionInitializer` the Micronaut `ApplicationContext` will be initialized and dependency injection will be performed on the function instance. You can use inject any bean using `jakarta.inject.Inject` as usual.

WARNING: Functions require a no argument constructor hence you must use field injection (which requires `lateinit` in Kotlin) when injecting dependencies into the function itself.

The `FunctionInitializer` super class provides numerous methods that you can override to customize how the `ApplicationContext` is built if desired.

=== Running Functions Locally

Raw functions cannot be executed locally. They can be tested by instantiating the function and inspecting any side effects by providing mock arguments or mocking dependent beans.

=== Deployment

When deploying the function to Cloud Function you should use the fully qualified name of the function class as the handler reference.

First build the function with:

```bash
$ ./gradlew clean shadowJar
```

Then `cd` into the `build/libs` directory (deployment has to be done from the location where the JAR file resides):

```bash
$ cd build/libs
```

To deploy the function make sure you have `gcloud` CLI then run:

```bash
$ gcloud beta functions deploy myfunction --entry-point example.function.Function --runtime java11 --trigger-http
```

In the example above `myfunction` refers to the name of your function and can be changed to whatever name you prefer to name your function. `example.function.Function` refers to the fully qualified name of your function class.

To obtain the trigger URL you can use the following command:

```bash
$ YOUR_HTTP_TRIGGER_URL=$(gcloud beta functions describe myfunction --format='value(httpsTrigger.url)')
```

You can then use this variable to test the function invocation:

```bash
$ curl -i $YOUR_HTTP_TRIGGER_URL
```
