plugins {
    id("io.micronaut.build.internal.gcp-module")
}

dependencies {
    annotationProcessor(mnSerde.micronaut.serde.processor)
    annotationProcessor(mnValidation.micronaut.validation.processor)
    api(libs.managed.google.cloud.pubsub)
    api(mn.micronaut.messaging)
    api(projects.micronautGcpCommon)
    compileOnly(mn.micronaut.http)
    compileOnly(mnValidation.micronaut.validation)
    implementation(mn.micronaut.json.core)
    implementation(mn.reactor)
    implementation(mnSerde.micronaut.serde.api)
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mnReactor.micronaut.reactor)
    testImplementation(mnRxjava3.micronaut.rxjava3)
    testImplementation(mnSerde.micronaut.serde.jackson)
    testImplementation(mnTestResources.testcontainers.core)
    testImplementation(mnValidation.micronaut.validation)
    testImplementation(testFixtures(projects.micronautGcpCommon))
    testRuntimeOnly(mn.micronaut.discovery.core)
}
