plugins {
    id("io.micronaut.build.internal.gcp-module")
    id("java-test-fixtures")
}

dependencies {
    api(libs.managed.google.auth.library.oauth2.http)
    api(libs.managed.google.cloud.core)
    compileOnly(mn.micronaut.discovery.core)
    compileOnly(mn.micronaut.http.client.core)
    implementation(mn.jackson.annotations)
    implementation(mn.micronaut.json.core)
    testAnnotationProcessor(mn.micronaut.inject.java)
    testFixturesApi(platform(mn.micronaut.core.bom))
    testImplementation(libs.system.stubs.core)
    testImplementation(mn.micronaut.discovery.core)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mnSerde.micronaut.serde.jackson)
}
