plugins {
    id("io.micronaut.build.internal.gcp-module")
}

dependencies {
    api(mn.micronaut.http.server)
    api(mnServlet.micronaut.servlet.core)
    api(projects.micronautGcpFunction)
    compileOnly(libs.managed.functions.framework.api)
    compileOnly(mn.micronaut.jackson.databind)
    implementation(mn.micronaut.http.netty)
    implementation(mn.micronaut.http.server)
    implementation(mn.micronaut.router)
    testAnnotationProcessor(mn.micronaut.inject.java)
    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
    testImplementation(libs.managed.functions.framework.api)
    testImplementation(mnRxjava3.micronaut.rxjava3)
    testImplementation(mnSerde.micronaut.serde.jackson)
}
