plugins {
    id 'java-library'
    id "io.micronaut.build.internal.gcp-testsuite"
    id "io.micronaut.build.internal.python"
}
dependencies {
    testImplementation(mnSerde.micronaut.serde.processor)
    testImplementation(mn.micronaut.inject.python.test)
    testImplementation(mn.micronaut.context.python)

    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.http.client)
}

tasks.withType(Test).configureEach {
    systemProperty "micronaut.python.pool.enabled", "false"
}
