== Accessing Secret Manager via client libraries

If you require access to Secret Manager via the Google link:https://cloud.google.com/pubsub/docs/quickstart-client-libraries[client java libraries], Micronaut provides a bean of type link:https://googleapis.dev/java/google-cloud-secretmanager/latest/com/google/cloud/secretmanager/v1/SecretManagerServiceClient.html[SecretManagerServiceClient] for injection.

snippet::io.micronaut.gcp.secretmanager.GoogleClientExample[tags="imports, clazz", source="main"]

<1> Inject SecretManagerServiceClient

=== Micronaut Secret Manager Client

If you rather not deal with Google gRPC libraries, internally the framework uses a wrapper client: api:gcp.secretmanager.client.SecretManagerClient[] that provides a reactive based approach:

snippet::io.micronaut.gcp.secretmanager.ClientExample[tags="imports, clazz", source="main"]

<1> Uses `latest` version and current project from `GoogleCloudCredentials`
<2> Uses current project but overrides version
<3> Fetches a secret from a different project

TIP: You can use the client libraries at any point in time of your runtime, however it's advised that secrets should be loaded only once during application startup, to reduce latency of the remote call as well as costs associated with secret retrieval.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-cloud-secret-manager-google.html[Use Google Secret Manager to store MySQL credentials] to learn more.
