plugins {
    id("io.micronaut.build.internal.gcp-module")
}

dependencies {
    api(mn.micronaut.http.client)
    api(projects.micronautGcpCommon)
    implementation(mn.reactor)
    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mnSerde.micronaut.serde.jackson)
}
