plugins {
    id "groovy"
    id "io.micronaut.build.internal.gcp-testsuite"
    id("io.micronaut.build.internal.kotlin-kapt")
}

dependencies {
    kapt(platform(mn.micronaut.core.bom))
    kapt(mn.micronaut.inject.java)
    testImplementation(platform(mn.micronaut.core.bom))
    testCompileOnly(mn.micronaut.inject.groovy)
    testImplementation(mnTest.micronaut.test.spock)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.http.client)
    testImplementation(projects.testSuiteUtils)
    implementation project(':micronaut-gcp-parameter-manager')
}
