plugins {
    id("groovy")
    id("io.micronaut.build.internal.gcp-testsuite")
}

dependencies {
    compileOnly(mn.groovy)
    compileOnly(mn.micronaut.inject.groovy)
    testCompileOnly(mn.micronaut.inject.groovy)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mnTest.micronaut.test.spock)
    testImplementation(platform(mn.micronaut.core.bom))
}

micronaut {
    testResources {
        // 10 minutes as this image is massive
        clientTimeout = 600
    }
}
