# WARNING: This file is a copy of the same one in:
#
# https://github.com/micronaut-projects/micronaut-project-template/tree/master/.github/workflows
#
# The only difference is that we don't use JDK 8. Any modification in the template needs to be applied manually here.
name: Maven Central Sync
on:
  release:
    types: [published]
jobs:
  central-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set the current release version
        id: release_version
        run: |
          release_version=${GITHUB_REF:11}
          sed -i "s/^projectVersion.*$/projectVersion\=${release_version}/" gradle.properties
          echo ::set-output name=release_version::${release_version}
      - name: Publish to Sonatype OSSRH
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_FILE: ${{ secrets.GPG_FILE }}
          PUBLISH_IN_2_STEPS: ${{ secrets.PUBLISH_IN_2_STEPS }}
        run: |
          echo $GPG_FILE | base64 -d > secring.gpg
          if [ -z ${PUBLISH_IN_2_STEPS+x} ]; then
            ./gradlew publish closeAndReleaseRepository
          else
            ./gradlew publish && ./gradlew closeAndReleaseRepository
          fi
