# WARNING: This file is a copy of the same one in:
#
# https://github.com/micronaut-projects/micronaut-project-template/tree/master/.github/workflows
#
# The only difference is that we don't use JDK 8. Any modification in the template needs to be applied manually here.
name: Java CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Optional setup step
        run: |
          [ -f ./setup.sh ] && ./setup.sh || true
      - name: Build with Gradle
        run: ./gradlew dependencyUpdates check --parallel --continue
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
      - name: Publish Test Report
        if: failure()
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Publish to JFrog OSS
        if: success() && github.event_name == 'push' && matrix.java == '11'
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew publish docs --no-daemon
      - name: Determine docs target repository
        uses: haya14busa/action-cond@v1
        id: docs_target
        with:
          cond: ${{ github.repository == 'micronaut-projects/micronaut-core' }}
          if_true: "micronaut-projects/micronaut-docs"
          if_false: ${{ github.repository }}
      - name: Publish to Github Pages
        if: success() && github.event_name == 'push' && matrix.java == '11'
        uses: micronaut-projects/github-pages-deploy-action@master
        env:
          TARGET_REPOSITORY: ${{ steps.docs_target.outputs.value }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BASE_BRANCH: ${{ env.githubBranch }}
          BRANCH: gh-pages
          FOLDER: build/docs
